version: "3.7"
services:
  mysqldb:
    image: "mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: steam_db
      MYSQL_USER: local_user
      MYSQL_PASSWORD: local_password
      MYSQL_ROOT_PASSWORD: local_password